name: Build check

on: push

jobs:
  build-check:
    strategy:
      matrix:
        platform: ['Windows Desktop', 'macOS', 'Linux', 'Web']
    runs-on: ${{ matrix.platform == 'macOS' && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          lfs: true

      - uses: chickensoft-games/setup-godot@v2
        name: Set up Godot
        with:
          version: 4.6.1
          use-dotnet: false
          include-templates: true

      - name: Clean project
        run: |
          rm -rf addons/gdUnit4
          rm -rf tests

      - name: Regenerate .godot folder
        run: |
          godot --editor --headless --quit

      - name: Build
        run: |
          output=$(godot --headless --export-release '${{ matrix.platform }}' 2>&1) || exit_code=$?
          echo "$output"

          if [ "${exit_code:-0}" -ne 0 ] || echo "$output" | grep -q "SCRIPT ERROR"; then
            exit 1
          fi
