name: Unit tests

on: push

jobs:
  unit-tests:
    runs-on: 'ubuntu-latest'

    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: MikeSchulze/gdUnit4-action@v1.3.0
        with:
          godot-version: '4.6.1'
          paths: res://test
          report-name: test_report.xml 
